## Numpy Introduction Part 1

In [1]:
!pip install numpy

In [2]:
import numpy as np

## What is an array?

An array is a data structure that stores a collection of items, usually of the same type, in a contiguous block of memory. It allows you to store multiple values under a single variable name and access them using indices (positions).

In Python, a NumPy array is an n-dimensional (ndarray) container that holds elements of the same data type, allowing efficient storage and fast numerical computations.

---

In [ ]:
# How to print 1 dimensional array
a= np.arange(10)  # 0 to 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# this command (a.shape) shows the dimension of the array like in pandas we use df.info() to see the info of dataframe
a.shape

(10,)

In [ ]:
# How print 2 dimensional array
# two box brackets show that it is 2D array
a2= a[np.newaxis, :]  # 0 to 9
print(a2)

[[0 1 2 3 4 5 6 7 8 9]]


In [9]:
a2.shape

(1, 10)

In [11]:
# How print 2 dimensional array
# two box brackets show that it is 2D array
a3= a2[np.newaxis, :]  # 0 to 9
print(a3)
a3.shape

[[[0 1 2 3 4 5 6 7 8 9]]]


(1, 1, 10)

## Creating arrays with numpy

In [38]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

## How to initialize arrays in numpy?

In [ ]:
ones = np.ones((2, 5)) # 2 rows and 5 columns
(ones)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
full = np.full((3, 4), 7) # 3 rows and 4 columns and fill with 7s
(full)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [21]:
# Creates an identity matrix (1’s on diagonal, 0 elsewhere)
identity = np.eye(4)
print(identity)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


We can also check the datatype of array by using this command (a.dtype)

In [23]:
identity.dtype

dtype('float64')

We can also check the type of array means which type of array it is , by using this command type(a)

In [24]:
type(identity)

numpy.ndarray

In short, 

type(a)           -> tells us type of array

dtype(a)           -> tells us data type of array elements


---

## Array Attributes

In [ ]:
# tell us shape of array
a.shape

(5,)

In [32]:
# tell us number of elements in array
b.size

6

In [33]:
# tell us lenght of elements in array
len(b)  

2

In [28]:
# tell us number of dimensions of array
a.ndim

1

---

## Basics Operations

In [39]:
a

array([1, 2, 3])

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# subtraction of two arrays
c = a - b
c

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [43]:
# addition of two arrays
d = a + b
d

array([[2, 4, 6],
       [5, 7, 9]])

In [44]:
# multiplication of two arrays
e = a * b
e

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [45]:
# division of two arrays
f = b / a
f

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [46]:
# if we want to square of each element in array
g = a ** 2
g

array([1, 4, 9])