## Numpy Part 2

In [ ]:
import numpy as np

In [2]:
empty=np.empty((3,4))
empty

array([[9.01932119e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.61590357e+184, 7.42383352e-091,
        1.48575042e-076],
       [3.63325437e+174, 1.25828428e-075, 3.99910963e+252,
        2.34403561e-056]])

In [7]:
x=np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## How to find the array of even numbers through range

In [8]:
even=np.arange(0,100,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
odd=np.arange(0,100,3)
odd

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# speicifc difference between numbers
diff=np.arange(1,100,5) # it makes a range from 1 to 100 with a difference of 5
diff

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
# we can use np.linspace() to create an array with values that are spaced linearly in a specified interval
linspace=np.linspace(0,20, num=10)
linspace

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
# define the dtype of the array
x=np.ones(2, dtype=np.float64)
x

array([1., 1.])

---

## Sorting an array

In [20]:
arr = np.array([3, 9, 5, 8, 5, 2])
arr

array([3, 9, 5, 8, 5, 2])

In [ ]:
#
np.sort(arr)

array([2, 3, 5, 5, 8, 9])

## How to add/join two arrays?

 Concatenate function add/ join two arrays

In [23]:
 a = np.array([1, 2, 3, 4, 5])
 b = np.array([6, 7, 8, 9, 10])
 np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Concatenate 2D arrays

In [33]:
a = np.array([[1, 2]])         # 1 by 2
b = np.array([[3, 4],[5, 6]])  # 2 by 2

# Concatenate 2D array
c = np.concatenate((a, b), axis=0)
print(c)


[[1 2]
 [3 4]
 [5 6]]


## Create a 3D array

In [34]:
# create a 3D array
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
len(d)

2

In [36]:
d.size

8

In [37]:
d.dtype

dtype('int64')

In [42]:
d.reshape(4, 2)
d.shape

(2, 2, 2)

In [43]:
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Convert 1D into 2D array

In [4]:
import numpy as np  # import numpy first

# first make a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a.shape)


(8,)


this (8,) show that 8 elements in one row

In [6]:
# then convert that into 2D array
a[np.newaxis, :].shape

(1, 8)

this (8,1) shows that 1 rows and 8 columns

## Convert 2D into 3D array

In [ ]:
# just add a new axis at the end of 2D array  
a[np.newaxis, np.newaxis, :].shape

(1, 1, 8)

## Indexing and slicing


In [13]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
a[2]


3

In [14]:
import numpy as np

a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(a)


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


## 1D Array Slicing

In [15]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[2:6]     # [30 40 50 60]
a[:4]      # [10 20 30 40]
a[4:]      # [50 60 70 80]


array([50, 60, 70, 80])

## Reverse slicing

In [16]:
a[::-1]     # reverse the array → [80 70 60 50 40 30 20 10]
a[-5:-1]    # from 4th last to 2nd last → [40 50 60 70]


array([40, 50, 60, 70])

## 2D Array Slicing

In [18]:
b = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])
b[1:3, 1:3]   # get a sub-array from rows 1-2 and columns 1-2


array([[ 6,  7],
       [10, 11]])

## 3D Array Slicing

In [20]:
c = np.array([
    [[1,  2,  3],
     [4,  5,  6]],

    [[7,  8,  9],
     [10, 11, 12]]
])
c[1, :, 1:]   # from 2nd block, get all rows and columns from index 1 onward


array([[ 8,  9],
       [11, 12]])

## Filter even numbers

In [21]:
b[b % 2 == 0] 

array([ 2,  4,  6,  8, 10, 12, 14, 16])