## Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
a = np.array([20, 30, 40, 50, 60, 70, 80, 10])
a

array([20, 30, 40, 50, 60, 70, 80, 10])

In [5]:
# this below function prints the number from 10 to 90 with the differenece of 10
b=np.arange(10, 90, 10)
b

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
## this function reshapes my 1D array b into 2 rows and 4 columns
c= b.reshape(2,4)
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
## now my 1D ray converts into 2D array (1st row become 1st index(means 0) and 2nd row becomes 2nd index (means 1) )
c[1]

array([50, 60, 70, 80])

In [8]:
c[c < 70]

array([10, 20, 30, 40, 50, 60])

## Enlist boolean operators conditional operators?

# Making an array from Data or another array

In [9]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [13]:
array1=a[40:45]
array1

array([200, 205, 210, 215, 220])

# Vertical Stack

In [15]:
a= np.array([[1,2,3,4,5,6]])
b=np.array([[7,8,9,10,11,12]])
c= np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Horizontol Stack

In [16]:
a= np.array([[1,2,3,4,5,6]])
b=np.array([[7,8,9,10,11,12]])
c= np.hstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

---

## Matrix or Matrices

In [17]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Array is totally differ from matrix , arrays have number of rows and columns

An array can have many dimensions, while a matrix is always a 2D array used for mathematical operations.

Arrays can be reshaped into any number of dimensions, while matrices can be reshaped only within 2D (rows × columns).

In [ ]:
# Create a matrix of big dimension
b=np.arange(0,100,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Now this above is array , not a matxix

Convert array into matrix


In [21]:
## this way of reshaping converts array into matrix
b=np.arange(0,100,2).reshape(10,5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

# Slicing a matrix

Matrix slicing means cutting out a part of the matrix by choosing certain rows and columns.

In [ ]:
# This 3;7 means rows from index 3 to 6 and 2:4 means columns from index 2 to 3
b[3:7, 2:4]

array([[34, 36],
       [44, 46],
       [54, 56],
       [64, 66]])

In [23]:
b[2:5,1:4]

array([[22, 24, 26],
       [32, 34, 36],
       [42, 44, 46]])

In [24]:
b[1:4,0:3]

array([[10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

In [25]:
b.min()

np.int64(0)

In [26]:
b.sum()

np.int64(2450)

# Add one matrix with another

In [ ]:
# First we make simple matrix
n=np.arange(1,51).reshape(5,10)
n
# Add one matrix with another
n+np.arange(51,101).reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

First make a simple matrix , then which type of matrix(menas of our own choice rows and columns) we want to make , just write like this 

n+np.arange(51,101).reshape(5,10) 

This adds 51 or 101 to every row and column

In [30]:
# Add one matrix with another
n+np.arange(51,101).reshape(5,10)

array([[ 52,  54,  56,  58,  60,  62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122, 124, 126, 128, 130],
       [132, 134, 136, 138, 140, 142, 144, 146, 148, 150]])

## Reversing a matrix

In [31]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

just use this function 

np.flip(b) 

this will reverse all the matrix

In [32]:
np.flip(b)

array([[98, 96, 94, 92, 90],
       [88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70],
       [68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50],
       [48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30],
       [28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10],
       [ 8,  6,  4,  2,  0]])